<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2005-02-21" />

<title>U.S. Professors salary during 2008-09</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">U.S. Professors salary during 2008-09</h1>
<h4 class="date">2005-02-21</h4>

</div>


<p>I am at this time (Feb, 2025) in the process of applying to phd
programs, as well as figuring out what I would like to do in the future.
For people in the research track, becoming a professor seems to be at
the end of this route. Whenever people ask me about future plans, I
would say do research and teach, two major aspect of a professor’s
life.</p>
<p>While I was browsing through the packages in R in search of the topic
for portfolio 2, I spotted this dataset about professors’ salary. I am
curious how much money professors earn back in 2008-09.</p>
<p>First, let’s load the package carData and the dataset Salaries.</p>
<pre class="r"><code>library(carData)
library(tidyverse)
library(car)
prof &lt;- Salaries</code></pre>
<p>Next, let’s take a look at the dataset. Like the labs we do, how many
observations are there? What are the variables in this dataset?</p>
<pre class="r"><code>nrow(prof)</code></pre>
<pre><code>## [1] 397</code></pre>
<pre class="r"><code>names(prof)</code></pre>
<pre><code>## [1] &quot;rank&quot;          &quot;discipline&quot;    &quot;yrs.since.phd&quot; &quot;yrs.service&quot;  
## [5] &quot;sex&quot;           &quot;salary&quot;</code></pre>
<p>There are 397 observations, and 6 variables. Variables include the
rank of professors (i.e., assistant, associate, or prof), discipline
these professors are in (i.e., theoretical or applied), years since
earning PhD, years of being a professor, the sex of the professor (i.e.,
female or male), and the nin-month salary in dollars.</p>
<p>Are males’ salary higher than females’?</p>
<pre class="r"><code>prof %&gt;% 
  filter(sex == &quot;Male&quot;) %&gt;% 
  summary()</code></pre>
<pre><code>##         rank     discipline yrs.since.phd    yrs.service        sex     
##  AsstProf : 56   A:163      Min.   : 1.00   Min.   : 0.00   Female:  0  
##  AssocProf: 54   B:195      1st Qu.:12.00   1st Qu.: 7.00   Male  :358  
##  Prof     :248              Median :22.00   Median :18.00               
##                             Mean   :22.95   Mean   :18.27               
##                             3rd Qu.:33.00   3rd Qu.:27.00               
##                             Max.   :56.00   Max.   :60.00               
##      salary      
##  Min.   : 57800  
##  1st Qu.: 92000  
##  Median :108043  
##  Mean   :115090  
##  3rd Qu.:134864  
##  Max.   :231545</code></pre>
<pre class="r"><code>prof %&gt;% 
  filter(sex == &quot;Female&quot;) %&gt;% 
  summary()</code></pre>
<pre><code>##         rank    discipline yrs.since.phd    yrs.service        sex    
##  AsstProf :11   A:18       Min.   : 2.00   Min.   : 0.00   Female:39  
##  AssocProf:10   B:21       1st Qu.:10.00   1st Qu.: 4.00   Male  : 0  
##  Prof     :18              Median :17.00   Median :10.00              
##                            Mean   :16.51   Mean   :11.56              
##                            3rd Qu.:23.50   3rd Qu.:17.50              
##                            Max.   :39.00   Max.   :36.00              
##      salary      
##  Min.   : 62884  
##  1st Qu.: 77250  
##  Median :103750  
##  Mean   :101002  
##  3rd Qu.:117002  
##  Max.   :161101</code></pre>
<p>First comment is that there were 358 male professors and only 39
female professors. The mean salary for female was 101,002, whereas the
mean salary for male was 115,090. It was a 14,000 difference. Wow!
Another comment, I would be happy with this salary.<br />
I want to conduct a t-test to see if this difference is significant.
First, run a couple assumption testing. Before t-test, check normality
and equal variance. For test of normality, I consulted: <a
href="https://www.sheffield.ac.uk/media/30585/download?attachment"
class="uri">https://www.sheffield.ac.uk/media/30585/download?attachment</a>.</p>
<pre class="r"><code>#create two separate variables, male_salary and female_salary, in order to run assumption testing. 
male_salary &lt;- prof %&gt;% 
  filter(sex == &quot;Male&quot;) %&gt;% 
  pull(salary)
female_salary &lt;- prof %&gt;% 
  filter(sex == &quot;Female&quot;) %&gt;% 
  pull(salary)
#normality testing
shapiro.test(male_salary)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  male_salary
## W = 0.95877, p-value = 1.735e-08</code></pre>
<pre class="r"><code>shapiro.test(female_salary)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  female_salary
## W = 0.94665, p-value = 0.06339</code></pre>
<pre class="r"><code>#equal variance testing, first change the sex column into numeric
prof &lt;- prof %&gt;% 
  mutate(sex_numeric = ifelse(sex == &quot;Male&quot;, 0, 1)) 
leveneTest(salary ~ sex, data = prof)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  0.8401 0.3599
##       395</code></pre>
<p>The normality test showed that male’s is significant. This probably
is fine because male has a large sample size, so it’s very likely to be
significant. Female’s is normal distribution. In addition, we can assume
equal variance. Now, let’s run the t-test.</p>
<pre class="r"><code>t.test(male_salary, female_salary, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  male_salary and female_salary
## t = 2.7817, df = 395, p-value = 0.005667
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   4131.107 24044.910
## sample estimates:
## mean of x mean of y 
##  115090.4  101002.4</code></pre>
<p>There is a significant difference between male and female
professors.</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
